name: Build server executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1-slim-bookworm
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build executable
        run: cargo build -r

      - name: Compress debug sections
        run: objcopy --compress-debug-sections target/release/server ./app

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./app
          if-no-files-found: error
          overwrite: true

